name: My workflow
on: push
jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Hello world"
  setup-python:
    runs-on: ubuntu-latest
    steps:
    - name: install-python
      uses: actions/setup-python@v5

    - name: python-v
      run: python --version
